# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('mental_activity', models.CharField(choices=[('N', 'None'), ('L', 'Light'), ('M', 'Moderate'), ('R', 'Rigorous')], default='N', max_length=1)),
                ('interested', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('distressed', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('excited', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('upset', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('strong', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('guilty', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('scared', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('hostile', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('enthusiastic', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('proud', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('irritable', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('alert', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('ashamed', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('inspired', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('nervous', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('determined', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('attentive', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('jittery', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('active', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
                ('afraid', models.CharField(choices=[('1', 'Very Slightly or Not At All'), ('2', 'A Little'), ('3', 'Moderately'), ('4', 'Quite a Bit'), ('5', 'Extremely')], default='3', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Your password must contain at least 8 characters.')], verbose_name='Password')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')], verbose_name='Last Name')),
                ('user_email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
