# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')], verbose_name='Last Name')),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Your password must contain at least 8 characters.')], verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('physical_activity', models.CharField(choices=[('N', 'None'), ('W', 'Once a week'), ('B', 'Twice a week'), ('T', 'Three times a week'), ('X', 'Four or more times a week')], default='N', max_length=1)),
                ('mental_activity', models.CharField(choices=[('N', 'None'), ('L', 'Light'), ('M', 'Moderate'), ('R', 'Rigorous')], default='N', max_length=1)),
                ('food_allergies', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')])),
                ('normal_preferences', models.CharField(choices=[('N', 'None'), ('W', 'Sweet'), ('S', 'Salty'), ('B', 'Bitter'), ('R', 'Sour'), ('U', 'Savory')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Your password must contain at least 8 characters.')], verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorprojectapp.User'),
        ),
    ]
